const VASES = [
    { id:1, name:'Postmodern Ceramic Vase', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:1200, volume:2 },
    { id:2, name:'Minimalist Ceramic Vase H', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:900, volume:4 },
    { id:3, name:'Classic White Ceramic Vase', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:800, volume:3 },
    { id:4, name:'Solid Black Ceramic Vase HQ07', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:550, volume:2 },
    { id:5, name:'The Naturlig Vase', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:300, volume:1 },
    { id:6, name:'Minimalist Ceramic Vase F', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:3000, volume:3 },
    { id:7, name:'Nordic Minimalist Ceramic Vase', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:450, volume:3 },
    { id:8, name:'Textured Ceramic Vase White', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:1000, volume:2 },
    { id:9, name:'Gold Glass Vase', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:250, volume:6 },
    { id:10, name:'Zen Porcelain Vase', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:700, volume:4 },
    { id:11, name:'Japanese Artisan Vase', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:350, volume:1 },
    { id:12, name:'Luna Vase', description:'No detail was spared in the pursuit of designing these truly spectacular vases. Not limited to just flowers, what makes each piece unique is it can be positioned as a stand-alone bud vase or even used to compliment you favourite decorative pieces. Guaranteed to brighten and lift any room, each vase will fit perfectly into your home or office, transforming that special space.', price:400, volume:1 }
]

export const getallVases = () => {
  return VASES;
}; 